from __future__ import annotations
"""Alert ORM model — stores farm condition alerts generated by the decision engine."""
import uuid
from datetime import datetime
from typing import Any
from sqlalchemy import String, DateTime, ForeignKey, JSON, func, Index
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.core.database import Base


class Alert(Base):
    __tablename__ = "alerts"

    id: Mapped[str] = mapped_column(
        String(64), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    field_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("fields.id", ondelete="CASCADE"), nullable=False
    )
    device_id: Mapped[str | None] = mapped_column(
        String(64), ForeignKey("devices.id", ondelete="SET NULL"), nullable=True
    )

    # Alert classification
    # type: "water_stress" | "heat_stress" | "excess_moisture" | "water_unavailable" | "activity_signal" | "sensor_error" | "device_offline"
    alert_type: Mapped[str] = mapped_column(String(64), nullable=False)

    # severity: "info" | "warning" | "critical"
    severity: Mapped[str] = mapped_column(String(16), nullable=False)

    # Human-readable content
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    explanation: Mapped[str] = mapped_column(String(1024), nullable=False)
    recommended_action: Mapped[str | None] = mapped_column(String(512), nullable=True)

    # Which sensor values triggered this alert (for transparency)
    contributing_factors: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)

    # Lifecycle
    # status: "active" | "acknowledged" | "resolved" | "expired"
    status: Mapped[str] = mapped_column(String(16), default="active", nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    acknowledged_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    resolved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Relationships
    field: Mapped["Field"] = relationship("Field", back_populates="alerts")

    __table_args__ = (
        Index("ix_alerts_field_status", "field_id", "status"),
        Index("ix_alerts_created_at", "created_at"),
    )

    def __repr__(self) -> str:
        return f"<Alert type={self.alert_type} severity={self.severity} status={self.status}>"
