"""Recommendation ORM model — irrigation and condition recommendations with full reasoning."""
import uuid
from datetime import datetime
from typing import Any
from sqlalchemy import String, DateTime, Float, ForeignKey, JSON, func, Index
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.core.database import Base


class Recommendation(Base):
    __tablename__ = "recommendations"

    id: Mapped[str] = mapped_column(
        String(64), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    field_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("fields.id", ondelete="CASCADE"), nullable=False
    )

    # type: "irrigation" | "environmental" | "crop_health"
    recommendation_type: Mapped[str] = mapped_column(String(32), nullable=False)

    # decision: "NORMAL" | "MONITOR" | "IRRIGATION_RECOMMENDED" | "IRRIGATION_BLOCKED" | ...
    decision: Mapped[str] = mapped_column(String(64), nullable=False)

    # severity: "none" | "low" | "medium" | "high" | "critical"
    severity: Mapped[str] = mapped_column(String(16), default="none", nullable=False)

    # Human-readable reasoning — the "why"
    reasoning: Mapped[str] = mapped_column(String(2048), nullable=False)

    # Individual factor contributions for transparency
    contributing_factors: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)

    # Whether this was generated by a rule or an ML model
    generated_by: Mapped[str] = mapped_column(
        String(16), default="rule_engine", nullable=False
    )  # "rule_engine" | "ml_model"

    # For ML-generated recommendations
    confidence_pct: Mapped[float | None] = mapped_column(Float, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Relationships
    field: Mapped["Field"] = relationship("Field", back_populates="recommendations")

    __table_args__ = (
        Index("ix_recommendations_field_created", "field_id", "created_at"),
        Index("ix_recommendations_type", "recommendation_type"),
    )

    def __repr__(self) -> str:
        return f"<Recommendation type={self.recommendation_type} decision={self.decision}>"
