/**
 * Alerts page — all active and historical alerts with acknowledge/resolve actions.
 */
import React, { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { formatDistanceToNow, parseISO } from 'date-fns';
import { api } from '../api/client';
import { StatusBadge } from '../components/ui/StatusBadge';
import type { Alert } from '../types';

const FARM_ID = 'farm-001';

const ALERT_TYPE_LABELS: Record<string, string> = {
  irrigation: 'Irrigation',
  heat_stress: 'Heat Stress',
  water_stress: 'Water Stress',
  excess_moisture: 'Excess Moisture',
  water_availability: 'Water Availability',
  activity_signal: 'Activity Signal',
  sensor_error: 'Sensor Error',
  device_offline: 'Device Offline',
};

export default function Alerts() {
  const [statusFilter, setStatusFilter] = useState<'active' | 'acknowledged' | 'resolved' | 'all'>('active');
  const queryClient = useQueryClient();

  const { data: alerts, isLoading } = useQuery<Alert[]>({
    queryKey: ['alerts', FARM_ID, statusFilter],
    queryFn: () => api.farms.alerts(FARM_ID, statusFilter === 'all' ? undefined : statusFilter),
    refetchInterval: 15000,
  });

  const acknowledge = useMutation({
    mutationFn: (id: string) => api.alerts.acknowledge(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['alerts'] }),
  });

  const resolve = useMutation({
    mutationFn: (id: string) => api.alerts.resolve(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['alerts'] }),
  });

  const activeCount = alerts?.filter(a => a.status === 'active').length ?? 0;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-6)', maxWidth: 900 }}>
      <div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-3)' }}>
          <h1 style={{ fontSize: 'var(--text-2xl)' }}>Alerts</h1>
          {activeCount > 0 && <span className="badge badge-critical">{activeCount} active</span>}
        </div>
        <p style={{ color: 'var(--color-text-muted)', fontSize: 'var(--text-sm)', marginTop: 4 }}>
          Farm condition alerts — generated by the decision engine when thresholds are exceeded.
        </p>
      </div>

      {/* Status filter */}
      <div style={{ display: 'flex', gap: 'var(--space-2)' }}>
        {(['active', 'acknowledged', 'resolved', 'all'] as const).map(s => (
          <button
            key={s}
            className={`btn btn-sm ${statusFilter === s ? 'btn-primary' : 'btn-secondary'}`}
            onClick={() => setStatusFilter(s)}
            style={{ textTransform: 'capitalize' }}
          >
            {s}
          </button>
        ))}
      </div>

      {/* Alerts list */}
      {isLoading ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }}>
          {[...Array(3)].map((_, i) => <div key={i} className="skeleton" style={{ height: 100 }} />)}
        </div>
      ) : !alerts?.length ? (
        <div className="card" style={{ textAlign: 'center', padding: 'var(--space-10)', color: 'var(--color-text-muted)' }}>
          <div style={{ fontSize: '2rem', marginBottom: 'var(--space-3)' }}>✓</div>
          <div style={{ fontSize: 'var(--text-base)', color: 'var(--color-text-secondary)' }}>
            No {statusFilter === 'all' ? '' : statusFilter} alerts
          </div>
          <div style={{ fontSize: 'var(--text-sm)', marginTop: 'var(--space-2)' }}>
            The decision engine is monitoring your farm continuously.
          </div>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }}>
          {alerts.map(alert => (
            <AlertCard
              key={alert.id}
              alert={alert}
              onAcknowledge={() => acknowledge.mutate(alert.id)}
              onResolve={() => resolve.mutate(alert.id)}
              loading={acknowledge.isPending || resolve.isPending}
            />
          ))}
        </div>
      )}
    </div>
  );
}

function AlertCard({ alert, onAcknowledge, onResolve, loading }: {
  alert: Alert;
  onAcknowledge: () => void;
  onResolve: () => void;
  loading: boolean;
}) {
  const severityBorder = alert.severity === 'critical' ? 'var(--color-status-critical-border)'
    : alert.severity === 'warning' ? 'var(--color-status-warning-border)'
    : 'var(--color-status-info-border)';

  return (
    <div className="card" style={{ borderLeftWidth: 3, borderLeftColor: severityBorder, borderLeftStyle: 'solid' }}>
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 'var(--space-3)', flexWrap: 'wrap' }}>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-2)', marginBottom: 'var(--space-2)', flexWrap: 'wrap' }}>
            <StatusBadge
              status={alert.severity === 'critical' ? 'critical' : alert.severity === 'warning' ? 'medium' : 'low'}
              label={alert.severity.toUpperCase()}
            />
            <span style={{ color: 'var(--color-text-muted)', fontSize: 'var(--text-xs)' }}>
              {ALERT_TYPE_LABELS[alert.alert_type] ?? alert.alert_type}
            </span>
            <span style={{ color: 'var(--color-text-muted)', fontSize: 'var(--text-xs)', marginLeft: 'auto' }}>
              {formatDistanceToNow(parseISO(alert.created_at))} ago
            </span>
          </div>

          <div style={{ fontWeight: 'var(--font-semibold)', fontSize: 'var(--text-base)', marginBottom: 'var(--space-2)' }}>
            {alert.title}
          </div>

          <div style={{ color: 'var(--color-text-secondary)', fontSize: 'var(--text-sm)', lineHeight: 1.6 }}>
            {alert.explanation}
          </div>

          {alert.recommended_action && (
            <div style={{
              marginTop: 'var(--space-3)',
              padding: 'var(--space-2) var(--space-3)',
              background: 'var(--color-surface-2)',
              borderRadius: 'var(--radius-sm)',
              fontSize: 'var(--text-xs)',
              color: 'var(--color-text-secondary)',
            }}>
              <span style={{ color: 'var(--color-text-muted)', fontWeight: 600, display: 'block', marginBottom: 2 }}>
                RECOMMENDED ACTION
              </span>
              {alert.recommended_action}
            </div>
          )}
        </div>

        {/* Actions */}
        {alert.status === 'active' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-2)', flexShrink: 0 }}>
            <button className="btn btn-secondary btn-sm" onClick={onAcknowledge} disabled={loading}>
              Acknowledge
            </button>
            <button className="btn btn-ghost btn-sm" onClick={onResolve} disabled={loading}>
              Resolve
            </button>
          </div>
        )}
        {alert.status !== 'active' && (
          <StatusBadge status={alert.status === 'acknowledged' ? 'monitor' : 'normal'} label={alert.status} />
        )}
      </div>
    </div>
  );
}
